'use strict';

const { Episode } = require('../models');

let options = {};
options.tableName = "Episodes"
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;
}

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    try {
      await Episode.bulkCreate([
        {
          userId: 1,
          showId: 1,
          episodeNumber: 1,
          episodeTitle: 'The Rise of AI',
          episodeDesc: 'An in-depth look at how artificial intelligence is shaping the tech industry and our daily lives.',
          guestInfo: "Jack Hart, Emma Lee",
          pubDate: "2022-06-03T08:24:52Z",
          duration: 45,
          size: null,
          tags: 'tech, AI, artificial intelligence',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 713
        },
        {
          userId: 1,
          showId: 1,
          episodeNumber: 2,
          episodeTitle: 'Blockchain Beyond Bitcoin',
          episodeDesc: 'Exploring the many uses of blockchain technology beyond cryptocurrency.',
          guestInfo: '',
          pubDate: "2023-07-07T01:04:40Z",
          duration: 45,
          size: null,
          tags: 'blockchain, tech, cryptocurrency',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 34
        },
        {
          userId: 1,
          showId: 1,
          episodeNumber: 3,
          episodeTitle: 'The Future of Wearable Tech',
          episodeDesc: 'How wearable technology is changing fitness, health, and entertainment.',
          guestInfo: "Ryan Cole",
          pubDate: null,
          duration: 45,
          size: null,
          tags: 'wearable tech, fitness, gadgets',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 655
        },
        {
          userId: 1,
          showId: 1,
          episodeNumber: 4,
          episodeTitle: 'Cybersecurity in 2024',
          episodeDesc: 'A discussion about the evolving challenges in cybersecurity and how to stay protected.',
          guestInfo: "Mia Park, Luke Ford",
          pubDate: "2024-09-17T14:30:29Z",
          duration: 45,
          size: null,
          tags: 'cybersecurity, tech, data privacy',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 34
        },

        // Fitness Fanatics Episodes
        {
          userId: 2,
          showId: 2,
          episodeNumber: 1,
          episodeTitle: '10 Tips for Building Muscle',
          episodeDesc: 'A complete guide to building muscle through weight training and proper nutrition.',
          guestInfo: '',
          pubDate: "2023-08-15T09:42:14Z",
          duration: 45,
          size: null,
          tags: 'fitness, muscle building, health',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 15
        },
        {
          userId: 2,
          showId: 2,
          episodeNumber: 2,
          episodeTitle: 'The Best Cardio Workouts',
          episodeDesc: 'Different types of cardio workouts and how to incorporate them into your routine for maximum fat burn.',
          guestInfo: "Ava Lane",
          pubDate: "2022-03-16T00:44:12Z",
          duration: 45,
          size: null,
          tags: 'cardio, fitness, health',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 648
        },
        {
          userId: 2,
          showId: 2,
          episodeNumber: 3,
          episodeTitle: 'Staying Motivated on Your Fitness Journey',
          episodeDesc: 'How to stay consistent and motivated as you work toward your fitness goals.',
          guestInfo: "Noah King",
          pubDate: "2023-02-14T14:37:12Z",
          duration: 45,
          size: null,
          tags: 'motivation, fitness, health',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 980
        },
        {
          userId: 2,
          showId: 2,
          episodeNumber: 4,
          episodeTitle: 'Nutrition for Athletes',
          episodeDesc: 'The best dietary choices for athletes to fuel performance and recovery.',
          guestInfo: '',
          pubDate: "2024-01-04T04:13:53Z",
          duration: 45,
          size: null,
          tags: 'nutrition, fitness, health',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 89
        },

        // Culinary Creations Episodes
        {
          userId: 3,
          showId: 3,
          episodeNumber: 1,
          episodeTitle: 'Mastering the Art of Italian Cooking',
          episodeDesc: 'A guide to classic Italian dishes and cooking techniques.',
          guestInfo: "Zoe Ray, Max Hale",
          pubDate: "2023-09-13T06:49:21Z",
          duration: 45,
          size: null,
          tags: 'Italian cuisine, cooking, food',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 733
        },
        {
          userId: 3,
          showId: 3,
          episodeNumber: 2,
          episodeTitle: 'Exploring the Flavors of Thailand',
          episodeDesc: 'A journey through the rich and vibrant flavors of Thai cuisine.',
          guestInfo: "Lily Page",
          pubDate: "2022-06-01T21:04:11Z",
          duration: 45,
          size: null,
          tags: 'Thai cuisine, cooking, food',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 73
        },
        {
          userId: 3,
          showId: 3,
          episodeNumber: 3,
          episodeTitle: 'Baking Like a Pro',
          episodeDesc: 'Tips and tricks for perfect baking, from cakes to cookies.',
          guestInfo: "Adam Wood, Ella Dean",
          pubDate: "2023-12-25T15:24:19Z",
          duration: 45,
          size: null,
          tags: 'baking, cooking, desserts',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 58
        },
        {
          userId: 3,
          showId: 3,
          episodeNumber: 4,
          episodeTitle: 'Vegan Cooking Made Easy',
          episodeDesc: 'Delicious and easy vegan recipes for every occasion.',
          guestInfo: '',
          pubDate: "2022-09-25T15:48:38Z",
          duration: 45,
          size: null,
          tags: 'vegan, cooking, food',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 49
        },

        // History Uncovered Episodes
        {
          userId: 4,
          showId: 4,
          episodeNumber: 1,
          episodeTitle: 'The Fall of the Roman Empire',
          episodeDesc: 'An exploration of the factors that led to the collapse of one of history’s greatest empires.',
          guestInfo: "Jake Hill",
          pubDate: "2022-01-16T11:22:36Z",
          duration: 45,
          size: null,
          tags: 'history, Roman Empire, ancient history',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 834
        },
        {
          userId: 4,
          showId: 4,
          episodeNumber: 2,
          episodeTitle: 'World War II: Turning Points',
          episodeDesc: 'Key events that shifted the course of World War II.',
          guestInfo: "Ruby Fox",
          pubDate: null,
          duration: 45,
          size: null,
          tags: 'history, World War II, military history',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 687
        },
        {
          userId: 4,
          showId: 4,
          episodeNumber: 3,
          episodeTitle: 'The Industrial Revolution',
          episodeDesc: 'How the Industrial Revolution transformed societies around the world.',
          guestInfo: "Owen West",
          pubDate: "2024-07-12T01:21:28Z",
          duration: 45,
          size: null,
          tags: 'history, Industrial Revolution, technology',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 88
        },
        {
          userId: 4,
          showId: 4,
          episodeNumber: 4,
          episodeTitle: 'Ancient Egypt: Pharaohs and Pyramids',
          episodeDesc: 'A look into the fascinating world of ancient Egypt and its incredible achievements.',
          guestInfo: "Ivy Neal, Eric Nash",
          pubDate: "2022-07-05T17:15:27Z",
          duration: 45,
          size: null,
          tags: 'history, ancient Egypt, pharaohs',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 946
        },

        // Health & Wellness Today Episodes
        {
          userId: 5,
          showId: 5,
          episodeNumber: 1,
          episodeTitle: 'The Importance of Mental Health',
          episodeDesc: 'Discussing the importance of mental well-being and how to maintain it.',
          guestInfo: "Maya Kent",
          pubDate: null,
          duration: 45,
          size: null,
          tags: 'mental health, wellness, health',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 567
        },
        {
          userId: 5,
          showId: 5,
          episodeNumber: 2,
          episodeTitle: 'Healthy Eating for a Busy Lifestyle',
          episodeDesc: 'Tips for maintaining a balanced diet while juggling a busy life.',
          guestInfo: "Levi Reed",
          pubDate: "2023-12-13T17:14:29Z",
          duration: 45,
          size: null,
          tags: 'healthy eating, wellness, health',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 345
        },
        {
          userId: 5,
          showId: 5,
          episodeNumber: 3,
          episodeTitle: 'Exercise for Stress Relief',
          episodeDesc: 'How physical activity can help relieve stress and improve overall well-being.',
          guestInfo: "Kate Moss",
          pubDate: "2024-11-30T02:22:44Z",
          duration: 45,
          size: null,
          tags: 'exercise, stress relief, wellness',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 734
        },
        {
          userId: 5,
          showId: 5,
          episodeNumber: 4,
          episodeTitle: 'Sleep: The Key to Health',
          episodeDesc: 'The importance of sleep for physical and mental health, and how to improve your sleep habits.',
          guestInfo: '',
          pubDate: null,
          duration: 45,
          size: null,
          tags: 'sleep, health, wellness',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 75
        },
        // True Crime Stories Episodes
        {
          userId: 6,
          showId: 6,
          episodeNumber: 1,
          episodeTitle: 'The Mystery of the Missing Heiress',
          episodeDesc: 'A deep dive into the disappearance of a wealthy heiress that shocked the nation.',
          guestInfo: "Sean Day, Nina Gale",
          pubDate: "2023-10-20T23:44:04Z",
          duration: 45,
          size: null,
          tags: 'true crime, mystery, missing person',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 34
        },
        {
          userId: 6,
          showId: 6,
          episodeNumber: 2,
          episodeTitle: 'The Serial Killer Next Door',
          episodeDesc: 'A chilling look at the double life of a man who turned out to be a serial killer.',
          guestInfo: "Evan Ross",
          pubDate: "2024-08-10T19:53:24Z",
          duration: 45,
          size: null,
          tags: 'serial killer, crime, mystery',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 6
        },
        {
          userId: 6,
          showId: 6,
          episodeNumber: 3,
          episodeTitle: 'The Unsolved Case of Jon Doe',
          episodeDesc: 'An exploration of a cold case that has baffled investigators for decades.',
          guestInfo: "Lily Wade",
          pubDate: "2022-11-06T16:37:57Z",
          duration: 45,
          size: null,
          tags: 'cold case, unsolved mystery, crime',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 74
        },
        {
          userId: 6,
          showId: 6,
          episodeNumber: 4,
          episodeTitle: 'Forensic Breakthroughs That Caught Killers',
          episodeDesc: 'How forensic science has been used to solve some of the most infamous crimes.',
          guestInfo: "Liam Nash, Anna Cole",
          pubDate: null,
          duration: 45,
          size: null,
          tags: 'forensics, true crime, investigation',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 257
        },

        // Mindful Living Episodes
        {
          userId: 7,
          showId: 7,
          episodeNumber: 1,
          episodeTitle: 'The Power of Meditation',
          episodeDesc: 'How meditation can improve mental and physical health.',
          guestInfo: "John Hunt",
          pubDate: "2024-07-06T07:11:58Z",
          duration: 45,
          size: null,
          tags: 'meditation, mindfulness, wellness',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 658
        },
        {
          userId: 7,
          showId: 7,
          episodeNumber: 2,
          episodeTitle: 'Living in the Present Moment',
          episodeDesc: 'Tips and techniques for practicing mindfulness in everyday life.',
          guestInfo: "Isla York",
          pubDate: "2022-06-03T08:24:52Z",
          duration: 45,
          size: null,
          tags: 'mindfulness, wellness, self-help',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 23
        },
        {
          userId: 7,
          showId: 7,
          episodeNumber: 3,
          episodeTitle: 'The Benefits of Yoga',
          episodeDesc: 'How yoga can enhance both physical and mental well-being.',
          guestInfo: '',
          pubDate: "2023-08-15T09:42:14Z",
          duration: 45,
          size: null,
          tags: 'yoga, wellness, mindfulness',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 32
        },
        {
          userId: 7,
          showId: 7,
          episodeNumber: 4,
          episodeTitle: 'Gratitude Practices for a Happier Life',
          episodeDesc: 'Exploring how practicing gratitude can transform your outlook and improve mental health.',
          guestInfo: "Mark Tate, Zoe Quinn",
          pubDate: "2022-03-16T00:44:12Z",
          duration: 45,
          size: null,
          tags: 'gratitude, mindfulness, self-improvement',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 467
        },

        // The Movie Buff Episodes
        {
          userId: 8,
          showId: 8,
          episodeNumber: 1,
          episodeTitle: 'The Best Films of the 21st Century',
          episodeDesc: 'A countdown of the top films released since the year 2000.',
          guestInfo: "Troy Beck",
          pubDate: "2024-01-04T04:13:53Z",
          duration: 45,
          size: null,
          tags: 'movies, best films, cinema',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 457
        },
        {
          userId: 8,
          showId: 8,
          episodeNumber: 2,
          episodeTitle: 'Underrated Movies You Need to Watch',
          episodeDesc: 'A list of movies that flew under the radar but are absolute must-watches.',
          guestInfo: '',
          pubDate: "2022-06-01T21:04:11Z",
          duration: 45,
          size: null,
          tags: 'movies, underrated films, cinema',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 345
        },
        {
          userId: 8,
          showId: 8,
          episodeNumber: 3,
          episodeTitle: 'The Rise of Superhero Films',
          episodeDesc: 'How superhero movies have dominated the box office and pop culture in the 21st century.',
          guestInfo: "Lucy Frye",
          pubDate: "2023-12-25T15:24:19Z",
          duration: 45,
          size: null,
          tags: 'superheroes, movies, cinema',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 30
        },
        {
          userId: 8,
          showId: 8,
          episodeNumber: 4,
          episodeTitle: 'Directors Who Defined the Decade',
          episodeDesc: 'Highlighting directors whose work shaped cinema in the 2010s.',
          guestInfo: "Kyle Gray",
          pubDate: "2022-09-25T15:48:38Z",
          duration: 45,
          size: null,
          tags: 'directors, movies, cinema',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 650
        },

        // The Entrepreneur's Corner Episodes
        {
          userId: 9,
          showId: 9,
          episodeNumber: 1,
          episodeTitle: 'How to Start a Successful Business',
          episodeDesc: 'A guide for aspiring entrepreneurs looking to turn their ideas into profitable ventures.',
          guestInfo: "Emma Bell",
          pubDate: "2022-01-16T11:22:36Z",
          duration: 45,
          size: null,
          tags: 'entrepreneurship, business, startups',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 785
        },
        {
          userId: 9,
          showId: 9,
          episodeNumber: 2,
          episodeTitle: 'Marketing Tips for Entrepreneurs',
          episodeDesc: 'Proven strategies for promoting your business and attracting customers.',
          guestInfo: "Matt Shaw",
          pubDate: "2022-07-05T17:15:27Z",
          duration: 45,
          size: null,
          tags: 'marketing, business, entrepreneurship',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 425
        },
        {
          userId: 9,
          showId: 9,
          episodeNumber: 3,
          episodeTitle: 'How to Scale Your Business',
          episodeDesc: 'Tips for growing your business beyond its initial phase and expanding your reach.',
          guestInfo: "Brad Ross",
          pubDate: "2024-11-30T02:22:44Z",
          duration: 45,
          size: null,
          tags: 'scaling, business, entrepreneurship',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 333
        },
        {
          userId: 9,
          showId: 9,
          episodeNumber: 4,
          episodeTitle: 'Entrepreneurs Who Changed the World',
          episodeDesc: 'A look at some of the most influential entrepreneurs in history and their legacies.',
          guestInfo: '',
          pubDate: "2023-10-20T23:44:04Z",
          duration: 45,
          size: null,
          tags: 'entrepreneurs, business, success',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 36
        },

        // Travel Tales Episodes
        {
          userId: 10,
          showId: 10,
          episodeNumber: 1,
          episodeTitle: 'Backpacking Across Europe',
          episodeDesc: 'Stories and tips from a backpacking trip across Europe, exploring its diverse cultures.',
          guestInfo: "Mia Cruz",
          pubDate: "2024-08-10T19:53:24Z",
          duration: 45,
          size: null,
          tags: 'travel, backpacking, Europe',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 673
        },
        {
          userId: 10,
          showId: 10,
          episodeNumber: 2,
          episodeTitle: 'Exploring Southeast Asia',
          episodeDesc: 'An adventure through the rich landscapes and cultures of Southeast Asia.',
          guestInfo: '',
          pubDate: "2022-11-06T16:37:57Z",
          duration: 45,
          size: null,
          tags: 'travel, Southeast Asia, adventure',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 552
        },
        {
          userId: 10,
          showId: 10,
          episodeNumber: 3,
          episodeTitle: 'The Best Hidden Gems in South America',
          episodeDesc: 'Discovering the most breathtaking but lesser-known destinations in South America.',
          guestInfo: "Jade Fox",
          pubDate: "2024-07-06T07:11:58Z",
          duration: 45,
          size: null,
          tags: 'travel, South America, hidden gems',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 969
        },
        {
          userId: 10,
          showId: 10,
          episodeNumber: 4,
          episodeTitle: 'Solo Travel: Pros and Cons',
          episodeDesc: 'Exploring the joys and challenges of traveling solo around the world.',
          guestInfo: "Nick Lane, Leah Wade",
          pubDate: "2022-03-16T00:44:12Z",
          duration: 45,
          size: null,
          tags: 'travel, solo travel, adventure',
          episodeUrl: "https://toginet.com/images/podvox/sample.mp3",
          episodeImage: null,
          explicit: false,
          published: false,
          prefix: null,
          downloads: 672
        }
      ])
    } catch(error) {
      console.error('Error during seeding episodes: ', error);
      throw error;
    }
  },

  async down (queryInterface, Sequelize) {
    options.tableName = 'Episodes';
    let episodes = await Episode.findAll();
    return queryInterface.bulkDelete(options, null, {})
  }
};
